
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SMART
 */
public class main extends javax.swing.JFrame {
//******************* intiall*****************************
   public static  Fridge fridge;
    public static void define(){
       Fridge p=new Fridge("orainge","2",true);
        fridge=p;
         p.next=new Fridge("water","5",true);
        p.next.next=new Fridge("onion","7",true);
    }   
           /**
     * Creates new form main
     */
    public main() {
        initComponents();
        define();
        showItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        itemComboBox = new javax.swing.JComboBox<>();
        itemText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 100, 30));

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 100, 30));

        jPanel1.add(itemComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 120, 30));

        itemText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTextActionPerformed(evt);
            }
        });
        itemText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemTextKeyTyped(evt);
            }
        });
        jPanel1.add(itemText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 130, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD NEW ITEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 380, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemTextActionPerformed

    private void itemTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemTextKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if( !(Character.isDigit(c)) && !(c>='a'&&c<='z') && !(c>='A'&&c<='Z')  &&  (c==KeyEvent.VK_BACK_SPACE) ){
            evt.consume();
                    }
        
    }//GEN-LAST:event_itemTextKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean check=RegulerItem();
if(check==false)
        JOptionPane.showMessageDialog(null, "     invalied data entry\n you should enter name and white space and number of item\n ex: apple 3");
else{
    addItem();
    showItem();
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        deleteItem();
        showItem();
    }//GEN-LAST:event_jButton1ActionPerformed

    //********************** REGX************
    boolean RegulerItem(){
   String rgx="[a-zA-Z]+\\s[0-9]+";
          Pattern p = Pattern.compile(rgx); 
    Matcher m;
     boolean b;     
         m=p.matcher(itemText.getText() );
        b=m.matches();
       
    return b;

 
}

//********************** SHOW ITEM************
    public static void showItem(){
        itemComboBox.removeAllItems();
        Fridge f=fridge;
           while(f !=null){
            if(f.state==true){
                 itemComboBox.addItem(f.item);
                System.out.println("now :"+f.item);
            }
            f=f.next;
           }
        }

    //********************** DELETE ITEM************
    public static void deleteItem(){
    String item_select=(String) itemComboBox.getSelectedItem();
       Fridge f=fridge;
          if(f.item.compareTo(item_select) ==0) {
          Fridge p=new Fridge(f.item,f.number,false);
          p.next=f.next;
          fridge=p;
          }
          else{
       while (f.next !=null){
           System.out.println("item is"+f.item);
           if(f.next.item.compareTo(item_select) ==0){
                    Fridge p=new Fridge(f.item,f.number,false);
                   p.next=f.next.next;
                   f.next=p;
           }
            f=f.next;
             }
          }
    }    
public static void addItem(){
        String item="";
        String number="";
        int count=0;
          while(itemText.getText().charAt(count) !=' '){
              item+=String.valueOf(itemText.getText().charAt(count));
              count++;
          }
          count++;
          while(count<itemText.getText().length()){
             number+=String.valueOf(itemText.getText().charAt(count));
              count++;
          }
             
          Fridge f= fridge;
             while (f.next !=null)
                            f=f.next;
                      Fridge p=new Fridge(item,number,true);
                    f.next=p;
 }
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> itemComboBox;
    public static javax.swing.JTextField itemText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
